stages:
  - mirror
  - test
  - stats
  - deploy
  - release

default:
  image: namboy94/ci-docker-environment:0.8.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa

github_mirror:
  stage: mirror
  tags: [docker]
  only: [master, develop]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/fat-ffipd.git
      master develop

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags: [docker]
  only: [master, develop]
  script:
    - python-unittest

type_check:
  stage: test
  tags: [docker]
  script:
    - python-static-type-check

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script:
    - pip install flask
    - sphinx-docgen

deploy_develop:
  stage: deploy
  tags: [privileged]
  only: [develop]
  before_script: []
  script:
    - docker build -f docker/Dockerfile -t fat-ffipd-dev . --no-cache
    - cp docker/docker-compose-dev.yml docker-compose.yml
    - echo "$ENV_FILE" > .env
    - docker-compose up -d --no-recreate
    - docker-compose up -d --no-deps fat-ffipd-dev-app
    - rm .env

deploy_production:
  stage: deploy
  tags: [privileged]
  only: [master]
  before_script: []
  script:
    - echo "TODO"

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - pypi-upload
