stages:
  - mirror
  - test
  - stats
  - deploy
  - release

default:
  image: namboy94/ci-docker-environment:0.8.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa

github_mirror:
  stage: mirror
  tags: [docker]
  only: [master, develop]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/fat-ffipd.git
      master develop

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags: [docker]
  only: [master, develop]
  script:
    - python-unittest

type_check:
  stage: test
  tags: [docker]
  script:
    - python-static-type-check

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script:
    - pip install flask
    - sphinx-docgen

deploy_develop:
  stage: deploy
  tags: [privileged]
  only: [master]
  before_script: []
  script:
    - docker build -t fat-ffipd-dev . --no-cache
    - docker stop fat-ffipd-dev-instance ||true
    - docker rm fat-ffipd-dev-instance ||true
    - docker run -d --restart always -p 5002:80
      --name fat-ffipd-dev-instance fat-ffipd-dev

deploy_production:
  stage: deploy
  tags: [privileged]
  only: [master]
  before_script: []
  script:
    - docker build -t fat-ffipd-dev . --no-cache
    - docker stop fat-ffipd-dev-instance ||true
    - docker rm fat-ffipd-dev-instance ||true
    - docker run -d --restart always -p 5001:80
      --name fat-ffipd-dev-instance fat-ffipd-dev

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - pypi-upload
