version: "3.2"
networks:
  net:
    driver: bridge
services:
  app:
    build: .
    image: "fat-ffipd-${DEPLOY_MODE}"
    depends_on:
      - db
    networks:
      - net
    volumes:
      - logs:/var/logs
    ports:
      - "${HTTP_PORT}:8000"
    env_file: .env
    environment:
      - DB_MODE=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - LOGGING_PATH=/var/logs
    restart: on-failure
  db:
    image: "mariadb:latest"
    env_file: .env
    networks:
      - net
volumes:
  logs: ~
