version: "3.2"
networks:
  net:
    driver: bridge
services:
  app:
    build: .
    image: "fat-ffipd"
    container_name: "fat-ffipd-app"
    depends_on:
      - db
    networks:
      - net
    volumes:
      - logs:/var/logs
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file: .env
    environment:
      - DB_MODE=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - LOGGING_PATH=/var/logs/fat_ffipd.log
      - DEBUG_LOGGING_PATH=/var/logs/fat_ffipd_debug.log
    restart: always
  db:
    image: "mariadb:10.1"
    container_name: "fat-ffipd-db"
    env_file: .env
    networks:
      - net
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    restart: always
volumes:
  logs: ~
  db_data: ~
